import 'dotenv/config'
const {
  PORT = 3000,
  NODE_ENV = 'development',
  DATABASE_URI_DEV,
  DATABASE_URI_PROD,
  PASSWORD_ADMIN_DEFAULT,
  SECRET_WORD,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
} = process.env

export default {
  NODE_ENV,
  PORT,
  DATABASE_URI_DEV,
  DATABASE_URI_PROD,
  PASSWORD_ADMIN_DEFAULT,
  SECRET_WORD,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
}
